name: Deploy amoapp

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        default: dev
        options: [dev, staging, prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}

    env:
      REMOTE_DIR: /var/www/app

    steps:
      - uses: actions/checkout@v4

      # Проверяем, что заданы ключ и окруженческие переменные
      - name: Assert config
        run: |
          [ -n "${{ secrets.SSH_KEY }}" ] || { echo "secrets.SSH_KEY is empty"; exit 1; }
          [ -n "${{ vars.DEPLOY_HOST }}" ] || { echo "vars.DEPLOY_HOST is empty"; exit 1; }
          [ -n "${{ vars.DEPLOY_USER }}" ] || { echo "vars.DEPLOY_USER is empty"; exit 1; }
          [ -n "${{ vars.DEPLOY_DIR }}" ] || { echo "vars.DEPLOY_DIR is empty"; exit 1; }

      - name: Setup SSH
        shell: bash
        run: |
          set -e
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # known_hosts (берём из секрета, иначе соберём сами)
          if [ -n "${{ secrets.KNOWN_HOSTS }}" ]; then
            printf '%s\n' "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -p "${{ vars.SSH_PORT || '22' }}" -H "${{ vars.DEPLOY_HOST }}" > ~/.ssh/known_hosts 2>/dev/null
          fi
          chmod 644 ~/.ssh/known_hosts

          {
            echo "Host target"
            echo "  HostName ${{ vars.DEPLOY_HOST }}"
            echo "  User ${{ vars.DEPLOY_USER }}"
            echo "  Port ${{ vars.SSH_PORT || '22' }}"
            echo "  IdentityFile ~/.ssh/id_ed25519"
            echo "  IdentitiesOnly yes"
            echo "  StrictHostKeyChecking yes"
          } > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Show target
        run: |
          echo "Deploying to ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }}:${{ vars.DEPLOY_DIR }}"
          echo "Environment: ${{ inputs.environment || 'dev' }}"

      - name: SSH ping
        run: ssh -o IdentitiesOnly=yes target "echo OK && whoami && hostname"

      - name: Rsync sources (exclude .venv)
        shell: bash
        run: |
          IFS=',' read -ra EXS <<< "${{ vars.RSYNC_EXCLUDES || '.git,.github,.DS_Store,.venv,*.log' }}"
          EX_ARGS=()
          for e in "${EXS[@]}"; do [ -n "$e" ] && EX_ARGS+=(--exclude "$e"); done

          rsync -azvv --itemize-changes --human-readable --delete \
            --no-perms --no-owner --no-group --omit-dir-times \
            "${EX_ARGS[@]}" \
            -e "ssh -o IdentitiesOnly=yes" \
            ./  target:"${{ vars.DEPLOY_DIR }}/"

      - name: Post-deploy (venv + deps + restart)
        run: |
          ssh -o IdentitiesOnly=yes target "bash -lc '
            set -euo pipefail
            cd \"${{ vars.DEPLOY_DIR }}\"
            python3 -m venv .venv || true
            . .venv/bin/activate
            python -m ensurepip --upgrade
            python -m pip install --upgrade pip wheel || python -m pip install --upgrade pip wheel --break-system-packages
            if [ -f requirements.txt ]; then
              python -m pip install -r requirements.txt || python -m pip install -r requirements.txt --break-system-packages
            fi
            sudo /usr/bin/systemctl restart amoapp.service
            sudo /usr/bin/systemctl status amoapp.service --no-pager | head -n 20 || true
          '"
